package com.dazzlersoft.webpos.model;
// Generated Jul 20, 2014 12:41:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long categoryId;
	private String categoryName;
	private String activityStatus;
	private String selected;
	
	public String getSelected() {
		return selected;
	}

	public void setSelected(String selected) {
		this.selected = selected;
	}

	private Set<Item> items = new HashSet<Item>(0);

	public Category() {
	}

	public Category(long categoryId, String categoryName, String activityStatus) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.activityStatus = activityStatus;
	}

	public Category(long categoryId, String categoryName,
			String activityStatus, Set<Item> items) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.activityStatus = activityStatus;
		this.items = items;
	}

	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getActivityStatus() {
		return this.activityStatus;
	}

	public void setActivityStatus(String activityStatus) {
		this.activityStatus = activityStatus;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
