package com.dazzlersoft.webpos.model;
// Generated Jul 20, 2014 12:41:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long imageId;
	private String imageFileName;
	private String imageKey;
	private Set<ItemInventory> itemInventories = new HashSet<ItemInventory>(0);

	public Image() {
	}

	public Image(long imageId, String imageFileName, String imageKey) {
		this.imageId = imageId;
		this.imageFileName = imageFileName;
		this.imageKey = imageKey;
	}

	public Image(long imageId, String imageFileName, String imageKey,
			Set<ItemInventory> itemInventories) {
		this.imageId = imageId;
		this.imageFileName = imageFileName;
		this.imageKey = imageKey;
		this.itemInventories = itemInventories;
	}

	public long getImageId() {
		return this.imageId;
	}

	public void setImageId(long imageId) {
		this.imageId = imageId;
	}

	public String getImageFileName() {
		return this.imageFileName;
	}

	public void setImageFileName(String imageFileName) {
		this.imageFileName = imageFileName;
	}

	public String getImageKey() {
		return this.imageKey;
	}

	public void setImageKey(String imageKey) {
		this.imageKey = imageKey;
	}

	public Set<ItemInventory> getItemInventories() {
		return this.itemInventories;
	}

	public void setItemInventories(Set<ItemInventory> itemInventories) {
		this.itemInventories = itemInventories;
	}

}
