package com.dazzlersoft.webpos.model;
// Generated Jul 20, 2014 12:41:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long itemId;
	private Category category;
	private String itemName;
	private String itemDescription;
	private String activityStatus;
	private Set<ItemInventory> itemInventories = new HashSet<ItemInventory>(0);

	public Item() {
	}

	public Item(long itemId, Category category, String itemName,
			String activityStatus) {
		this.itemId = itemId;
		this.category = category;
		this.itemName = itemName;
		this.activityStatus = activityStatus;
	}

	public Item(long itemId, Category category, String itemName,
			String itemDescription, String activityStatus, Set<ItemInventory> itemInventories) {
		this.itemId = itemId;
		this.category = category;
		this.itemName = itemName;
		this.itemDescription = itemDescription;
		this.activityStatus = activityStatus;
		this.itemInventories = itemInventories;
	}

	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public String getActivityStatus() {
		return this.activityStatus;
	}

	public void setActivityStatus(String activityStatus) {
		this.activityStatus = activityStatus;
	}

	public Set<ItemInventory> getItemInventories() {
		return this.itemInventories;
	}

	public void setItemInventories(Set<ItemInventory> itemInventories) {
		this.itemInventories = itemInventories;
	}

}
