package com.dazzlersoft.webpos.model;
// Generated Jul 20, 2014 12:41:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemInventory generated by hbm2java
 */
public class ItemInventory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long itemInventoryId;
	private Image image;
	private Item item;
	private int quantityAvailable;
	private BigDecimal unitPrice;
	private String color;
	private BigDecimal itmSize;
	private BigDecimal weight;
	private String sizeMeasurementUnit;
	private String weightMeasurementUnit;
	private Date startDate;
	private Date endDate;
	private String activityStatus;

	public ItemInventory() {
	}

	public ItemInventory(long itemInventoryId, Image image, Item item,
			int quantityAvailable, BigDecimal unitPrice, Date startDate,
			String activityStatus) {
		this.itemInventoryId = itemInventoryId;
		this.image = image;
		this.item = item;
		this.quantityAvailable = quantityAvailable;
		this.unitPrice = unitPrice;
		this.startDate = startDate;
		this.activityStatus = activityStatus;
	}

	public ItemInventory(long itemInventoryId, Image image, Item item,
			int quantityAvailable, BigDecimal unitPrice, String color,
			BigDecimal itmSize, BigDecimal weight, String sizeMeasurementUnit,
			String weightMeasurementUnit, Date startDate, Date endDate,
			String activityStatus) {
		this.itemInventoryId = itemInventoryId;
		this.image = image;
		this.item = item;
		this.quantityAvailable = quantityAvailable;
		this.unitPrice = unitPrice;
		this.color = color;
		this.itmSize = itmSize;
		this.weight = weight;
		this.sizeMeasurementUnit = sizeMeasurementUnit;
		this.weightMeasurementUnit = weightMeasurementUnit;
		this.startDate = startDate;
		this.endDate = endDate;
		this.activityStatus = activityStatus;
	}

	public long getItemInventoryId() {
		return this.itemInventoryId;
	}

	public void setItemInventoryId(long itemInventoryId) {
		this.itemInventoryId = itemInventoryId;
	}

	public Image getImage() {
		return this.image;
	}

	public void setImage(Image image) {
		this.image = image;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public int getQuantityAvailable() {
		return this.quantityAvailable;
	}

	public void setQuantityAvailable(int quantityAvailable) {
		this.quantityAvailable = quantityAvailable;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public BigDecimal getItmSize() {
		return this.itmSize;
	}

	public void setItmSize(BigDecimal itmSize) {
		this.itmSize = itmSize;
	}

	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public String getSizeMeasurementUnit() {
		return this.sizeMeasurementUnit;
	}

	public void setSizeMeasurementUnit(String sizeMeasurementUnit) {
		this.sizeMeasurementUnit = sizeMeasurementUnit;
	}

	public String getWeightMeasurementUnit() {
		return this.weightMeasurementUnit;
	}

	public void setWeightMeasurementUnit(String weightMeasurementUnit) {
		this.weightMeasurementUnit = weightMeasurementUnit;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getActivityStatus() {
		return this.activityStatus;
	}

	public void setActivityStatus(String activityStatus) {
		this.activityStatus = activityStatus;
	}

}
